name: ci

on:
  workflow_dispatch:
  # 每天 6:10 (UTC+8) 触发一次
  schedule:
    - cron: '10 14 * * *'
  push:
    branches:
      - main

jobs:
  massgravel:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Add token
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set variables
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo "BUILDTIME=$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "REPODIR=$PWD" >> $GITHUB_ENV
          echo "GITHUB_OWNER=massgravel" >> $GITHUB_ENV
          echo "GITEE_OWNER=peiyingyao" >> $GITHUB_ENV
          echo "REPOS_MIRROR_LIST=Microsoft-Activation-Scripts,massgrave.dev,activated.win,get.activated.win" >> $GITHUB_ENV
          echo "REPOS_MIRROR_MAPPINGS=" >> $GITHUB_ENV
          echo "REPOS_MIRROR_FORCE_UPDATE=true" >> $GITHUB_ENV
          echo "::debug"

      - name: Mirror repositories to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/${{ env.GITHUB_OWNER }}
          dst: gitee/${{ env.GITEE_OWNER }}
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: ${{ env.REPOS_MIRROR_LIST }}
          mappings: ${{ env.REPOS_MIRROR_MAPPINGS }}
          force_update: ${{ env.REPOS_MIRROR_FORCE_UPDATE }}
          debug: true
          timeout: 60
